language: node_js
node_js:
  - node
env:
  - TEST_DIR=client
  - TEST_DIR=server
before_install:
  - cd $TEST_DIR
cache:
  directories:
    - "$TEST_DIR/node_modules"
  yarn: true
before_depoly:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: Aw2hGmC5AdT1LlmZS5pwlQoPjnTC3yXrsPb52fTisbupUEJ64vfDH5r5JVvHujtnqJqWJKJr60yjks9w/s8uPUlHlMtg4FYCtS4cje6DgjyhBSjqkzaDuvieL0DMGbu5vYVwlSSb7MRPQeVrf35kG+VpKHSGnUoArKZ5mdy2eKxQBX3tAYLyfXfuDMSQ9do2bz/F0UzTW55sleiua3Wvs9N4E/HaL4PcCqdwIu2G8ygcBYxmn5e+r0KATqzQBowjXwVt55cUsV8dvk+sYq+TvdSxKm+8rsFfcnN4PuSe7dfWQfOEe5ACRGhSd538aKEo1W4EO+4n+C0A4CSmIRl5FgkS8E1B7wNAOcnAGalci7KAfwolIKrz9e0fz5dfEsu6Ov4hMqCcYl+zzerwrZathV0327qtb8/cMPV1RJiSh9aOJMSmo0vjHc447OKv/1YmPEBrEVIkWdfk7RnB9OzTRKBHj8m2ex0S9khHHeRPCoSNP0tMPpZoZIi7TolYJc+4q3hlZbPbxhvxjWx4Q2ANnDvErLk0BY+kbDoKJgPTc50M4jKkIPwm3Z7PwcGvadBVUzX0F0iGOWpXsyBRlyvv1I00loOpEpadqhOITwqYscogW9FUpUXp1zCutFqxnzF3x1vNt/vlNXVSD230gTkZy4lGBhZNnPuulZ+lKH8CU6Q=
  app: teacher-portal
  on:
    repo: codebase-berkeley/teacher-portal
    condition: $TEST_DIR=server
    branch: heroku
